### ISSUE TITLE
Sound issue

### ISSUE THREAD

**Issue by DFTOM** [MrCrayfish/MrCrayfishGunMod#180] opened 2021-06-09 11:56 UTC
Doesn't hear anything but guns sound ( guns mod version 1.0.1-1.16.3 )

**Comment by Ch1216** [comment] 2021-12-09 03:38
does it still happen?

**Comment by MrCrayfish** [comment] 2022-07-13 13:13
Closing since unable to reproduce.

**Closed as completed by MrCrayfish** 2022-07-13 13:13 UTC
