### ISSUE TITLE
Bullet issue when logging out from a server

### ISSUE THREAD

**Issue by Nelly1234567** [MrCrayfish/MrCrayfishGunMod#35] opened 2019-10-21 22:12 UTC
There seems to be an issue with the bullet rendering when players log out from a server after guns have been used (whether near them or not and whether they used them or not).

An example crash log from two different players can be found in the following links:
https://paste.dimdev.org/umocimirat.mccrash
https://paste.dimdev.org/fedejaqifa.mccrash

Is there a way I can temporarily turn off the projectile rendering until this gets resolved?

Thanks!

**Comment by MrCrayfish** [comment] 2021-02-03 11:56
Duplicate of https://github.com/MrCrayfish/MrCrayfishGunMod/issues/30

**Closed by MrCrayfish** 2021-02-03 11:56 UTC
