### ISSUE TITLE
Bazooka and Grenade don't respect FTBUtils claims

### ISSUE THREAD

**Issue by Sven65** [MrCrayfish/MrCrayfishGunMod#95] opened 2020-11-26 13:23 UTC
Gun mod version: `0.15.3`

As the title says, using this mod on a server with FTBUtils, the bazooka and Grenade bypass the FTBUtils chunk claiming.

**Comment by MrCrayfish** [comment] 2022-07-13 13:00
Duplicate of https://github.com/MrCrayfish/MrCrayfishGunMod/issues/42

**Closed as completed by MrCrayfish** 2022-07-13 13:00 UTC
Labels: 1.12
