### ISSUE TITLE
Cannot Shoot while scoped In

### ISSUE THREAD

**Issue by Hexerious** [MrCrayfish/MrCrayfishGunMod#348] opened 2022-08-08 16:21 UTC
I am using the 1.19 version and the guns shoot fine when not scoped, but when i scope the gun will not shoot whatsoever. The medium scope has some sort of yellow light blocking my view. If anyone knows how to fix please reply asap.

Mod is version 1.2.8
forge version is 41.1.0

**Comment by BlackWarrior2004** [comment] 2022-08-23 19:01
I second this my mod version is 1.2.8, minecraft 1.19.2 and forge 43.1.1

**Comment by BlackWarrior2004** [comment] 2022-08-23 19:10
Also another thing, I cant open attachments normally, after I press Z, it does nothing, but when I try to scope in after that(right click), it opens the attachments

**Comment by individual217** [comment] 2022-10-26 02:54
I also experience this with forge 43.1.43 and mod version 1.2.8, but only certain guns have problems shooting while scoping in and my boyfriend can shoot some guns that I can't. He can shoot the heavy rifle, while I can't. We both can't shoot the pistol, and both of us can shoot the assault rifle.

**Comment by MrCrayfish** [comment] 2022-10-26 05:15
Unfortuantely I'm unable to reproduce the issue. Everything seems to work on my side, however it's likely a combination of mods or potentially LAN causing issues. Can someone send a list of mods you are using (or the curseforge modpack link/profile export)?
Are you guys also playing on a server, LAN or singleplayer?

**Comment by individual217** [comment] 2022-10-26 05:48
I am playing on a server using the All the Mods 8 modpack. This mod is not normally in the pack, we added it ourselves

**Comment by MrCrayfish** [comment] 2023-01-09 12:29
You are using a shield. This will be fixed in 1.3.0

**Closed as completed by MrCrayfish** 2023-01-09 12:29 UTC
