### ISSUE TITLE
The ?7java.lang.reflect.InvocationTargetException: null

### ISSUE THREAD

**Issue by Scribeseer** [MrCrayfish/MrCrayfishGunMod#322] opened 2022-07-13 05:20 UTC
Framework (framework) has failed to load correctly
?7java.lang.reflect.InvocationTargetException: null,
        MrCrayfish's Gun Mod (cgm) has failed to load correctly
?7java.lang.reflect.InvocationTargetException: null 
HOW DO I FIX THIS PLEASE HELP I REALLY WANNA MESS AROUND WITH THE MOD :(

**Comment by MrCrayfish** [comment] 2022-07-13 14:46
Duplicate of https://github.com/MrCrayfish/MrCrayfishGunMod/issues/321

**Closed as completed by MrCrayfish** 2022-07-13 14:46 UTC
Labels: 1.19
