### ISSUE TITLE
Guns unable to reload (1.18.1-Forge_39.0.10)

### ISSUE THREAD

**Issue by kemoyue** [MrCrayfish/MrCrayfishGunMod#239] opened 2022-01-15 06:59 UTC
All the players on server can not reload any guns.

But you can fix it with the following method:
Deleted server files "/config/cgm-common.toml" and "/world/serverconfig/cgm-server.toml", with no any gun mod items lost.

Reloading after being floated by a shulker may cause this issue.
But i have no idea at all...

1.18.1-Forge_39.0.10

Mod list:
AppleSkin 2.2.0
Backpacked 2.0.0
Better Advancements 0.1.2.122
BetterF3 1.2.2 (If server unable to launch, remove this mod on server side)
Carry On 1.17.0.5
Catalogue 1.6.0
Cloth Config v4 API 6.1.48
Configured 1.5.1
Controlling 9.0.8
Create 0.4b
Curios API 1.18.1-5.0.4.2
Dungeon Crawl 2.3.6
EnchantmentDescriptions 9.0.8
Farmer's Delight 1.18.1-1.0.1
FastLeafDecay 27.2
Flywheel 1.18-0.5.0a
Framework 0.2.2
Gobber 2 2.6.11
Infernal Mobs 1.18.1
Just Enough Items 9.1.2.61
Just Enough Resources 0.13.1.138
MrCrayfish's Gun Mod 1.1.2
Polymorph 1.18.1-0.35
Posture 1.0.0
Simple Inventory Sorter 19.0.0
Storage Drawers 10.1.0
ToroHealth 1.18-forge-2 (If server unable to launch, remove this mod on server side)
Valhelsia Core 1.18.1-0.3.0
Valhelsia Structures 1.18.1-0.1.0
Xaero's Minimap 21.23.0
Xaero's World Map 1.19.0

**Comment by MrCrayfish** [comment] 2022-01-15 14:25
Thanks for the report. This has been a unsolveable issue for a while, I've spent hours looking for what may be the cause. The biggest problem I am having is not being able to replicate the issue. Simply put it, when I host a server and join it, everything works as normal. Are you able to answer a few questions:
1. Was there a certain event that happened that stopped you from reloading?
2. Did this affect all players at the same time or one by one?
3. Are you using alternative server software, such as Mohist or Magma?
4. Did the issue only occur after relogging into the server or while playing only?

Can you also send the full debug log of the clients and server involved with the issue?

Also just to note, the config is unlikely the cause. I am assuming you restarted your server after deleting it. The config has no relation to the reloading logic.

**Comment by MrCrayfish** [comment] 2022-01-15 15:52
Along wtih the previous message, would you be willing to test a custom version of the mod that has extra logging? This would need to be installed on your client and server.

**Comment by MrCrayfish** [comment] 2022-01-15 16:15
Here is the custom version. Make sure you extract the zip, it contains the jar file.
[gun-mod-1.1.3-1.18.1.zip](https://github.com/MrCrayfish/MrCrayfishGunMod/files/7875342/gun-mod-1.1.3-1.18.1.zip)

**Comment by kemoyue** [comment] 2022-01-15 20:18
Thank you for reply!

1. There isn't any certain event cause this issue.
2. It affect all players at the same time.
3. I'm using the native forge server.
4. This issue accurs while playing at the end dimension, when after being floated by a shulker.

This issue appears as infinitely repeating reload animation but not actual reload.

Server logs at that time has no any error output and any suspicious output.

When this issue accurs then i restarted server. but cant reload still.
So i shutdown server and delete cgm config files. Then start server, the issue disappeared (Looks like nothing happend).
After that, I can't reproduce this issue again.

I'd like to test custom version mod with extra logging.
I will upload the Logs if I find anything.

**Comment by MrCrayfish** [comment] 2022-01-16 03:40
> This issue appears as infinitely repeating reload animation but not actual reload.

Does the reload sound also play?

**Comment by kemoyue** [comment] 2022-01-16 08:35
No. Reload animation without sound( OH NO , I DONT REMEMBER. SORRY..... BUT IT SEEMS NO SOUND PLAYS WHEN RELOADING ). Inventory bar bullet indicator does not increase. But if you have a full bullet gun and fire, inventory bullet indicator does decrease ammo, look like works all good. just can't reload.

(I had try many ways to trigger this issue. But all things works fine now. )
Does network package lost effect that? Or Client and Server mods not sync?
Cause my client multiplayer server list shows a red X icon at right. It shows "Incompatible FML modded server \n Server mod list is not compatible"
If delete client mods "tolohealth" and "betterf3", That red X icon becomes green √ icon.

**Comment by MrCrayfish** [comment] 2022-01-16 09:02
Packets are not lost since Minecraft uses TCP for it's connections. Since betterf3 is not installed on the server, it's still checking if it matches the server list. It will say incompatible but it's still joinable.

Just keep using the custom version until you run into the issue again.

**Comment by MrCrayfish** [comment] 2022-01-22 11:42
Any update on this?

**Comment by spooksgit** [comment] 2022-02-02 01:02
try ToughAsNails enable_temperature = true
ToughAsNails-1.18.1-6.0.0.68-universal to replicate the issue
> Any update on this?

**Comment by MrCrayfish** [comment] 2022-02-02 14:03
Mod is not mentioned on the original post. Are you using the latest version of Framework?

**Comment by spooksgit** [comment] 2022-02-02 14:38
> Mod is not mentioned on the original post. Are you using the latest version of Framework?

yes

**Comment by MrCrayfish** [comment] 2022-02-02 14:41
And that version is?

**Comment by spooksgit** [comment] 2022-02-02 14:45
> And that version is?

framework-0.2.3-1.18.1.jar
cgm-1.1.3-mc1.18.1.jar

**Comment by spooksgit** [comment] 2022-02-02 15:08
Full mod list on jdk-17.0.1.12-hotspot
alexsmobs-1.16.0.jar
architectury-3.6.14.jar
artifacts-1.18.1-4.0.2.jar
backpacked-2.0.2-1.18.1.jar
BetterPingDisplay-1.18.1-1.1.jar
BetterThirdPerson-Forge-1.18-1.6.0.jar
BiomesOPlenty-1.18.1-15.0.0.105-universal.jar
carryon-1.18.1-1.17.0.7.jar
cgm-1.1.3-mc1.18.1.jar
chalk-1.18.1-1.2.0.jar
chococraft-1.18.1-0.2.2.jar
citadel-1.10.8-1.18.jar
collective-1.18.1-3.8.jar
comforts-forge-1.18-5.0.0.1.jar
Companion-1.18-forge-1.1.1.jar
configured-1.5.1-1.18.1.jar
connectedglass-1.1.1-mc1.18.jar
controllable-0.15.1-mc1.18.1.jar
corpse-1.18.1-1.0.4.jar
CreativeCore_v2.4.1_mc1.18.1.jar
creeperoverhaul-1.18.1-0.3.0-forge.jar
curios-forge-1.18.1-5.0.6.0.jar
CustomStartingGear-1.18.1-2.0.3.1-universal.jar
DamageTilt-1.18-forge-0.1.1.jar
DoggyTalents-1.18.1-2.4.2.jar
DungeonCrawl-1.18.1-2.3.6.jar
dusk-1.18-1.7.jar
effective_for_forge-1.001.jar
Enhanced-Farming-1.18.1-1.2.5.1.jar
EnhancedVisuals_v1.4.4_mc1.18.1.jar
expandability-5.0.0-forge.jar
FallingTree-1.18.1-3.2.0b2.jar
FastWorkbench-1.18.1-6.0.0.jar
ferritecore-4.0.0-forge.jar
firstjoinmessage_1.18.1-1.4.jar
flashnpcs-1.18.1-1.1.4.jar
flywheel-forge-1.18-0.6.0.jar
framework-0.2.3-1.18.1.jar
furniture-7.0.0-pre28-1.18.1.jar
geckolib-1.18-forge-3.0.11.jar
HunterIllager-1.18.1-3.1.3.jar
HyperLighting-1.18.1-1.2.jar
jei-1.18.1-9.2.3.84.jar
Kiwi-1.18-forge-5.2.5.jar
lazydfu-1.0-1.18+.jar
mcw-bridges-2.0.1-mc1.18.1.jar
physics-mod-2.6.6-mc-1.18-forge.jar
Placebo-1.18.1-6.0.5.jar
PlayerRevive_v2.0.0-pre07_mc1.18.1.jar
polymorph-forge-1.18.1-0.36.jar
posture-1.0.0-mc1.18.jar
simplylight-1.18.1-1.4.0-build.26.jar
sit-1.18-1.3.1.jar
SoL-Carrot-1.18.1-1.12.0.jar
soundphysics-forge-1.18.1-1.0.4.jar
swingthroughgrass-1.18.1-1.8.0.jar
TerraBlender-forge-1.18.1-1.1.0.73.jar
ToughAsNails-1.18.1-6.0.0.68-universal.jar
valhelsia_core-1.18.1-0.3.2.jar
valhelsia_structures-1.18.1-0.1.1.jar
voicechat-forge-1.18.1-2.2.13.jar
walljump-forge-1.18.1-1.3.7.jar
Xaeros_Minimap_22.1.3_Forge_1.18.jar
zombify-villager-1.18.1-forge-0.9.9.jar
fmlcore-1.18.1-39.0.63.jar
javafmllanguage-1.18.1-39.0.63.jar
mclanguage-1.18.1-39.0.63.jar
server-1.18.1-20211210.034407-srg.jar
forge-1.18.1-39.0.63-universal.jar

**Comment by spooksgit** [comment] 2022-02-02 15:14
by default enable_temperature = false
you need to enable it from mapname/serverconfig/toughasnails-server.toml

**Comment by MrCrayfish** [comment] 2022-04-30 05:54
Issue should be fixed. Ensure you are now using the latest Framework and Gun Mod

**Closed as completed by MrCrayfish** 2022-04-30 05:54 UTC
