### ISSUE TITLE
any gun is not reloding

### ISSUE THREAD

**Issue by Hedtosea** [MrCrayfish/MrCrayfishGunMod#88] opened 2020-09-09 02:41 UTC
i am pressing r with every weapon but i have the same bullet type it requires 
i am in version 1.12.2 i checked out the config files but cant find where the keybind is

**Comment by MrCrayfish** [comment] 2021-02-03 12:17
Duplicate of https://github.com/MrCrayfish/MrCrayfishGunMod/issues/39

**Closed as completed by MrCrayfish** 2021-02-03 12:17 UTC
