### ISSUE TITLE
Can't reload in 1.18.1

### ISSUE THREAD

**Issue by SRR8** [MrCrayfish/MrCrayfishGunMod#223] opened 2021-12-13 14:31 UTC
Installed the mod, could fire and reload. Came back the next day with no mod changes, and now no-one can reload.

**Comment by MrCrayfish** [comment] 2021-12-13 14:50
You probably installed a mod that overrides the R button.

**Comment by SRR8** [comment] 2021-12-13 15:14
I thought so too, so I set the keybind to other keybinds with no conflicts and still no luck.
Even so it worked when first installed but when we loaded up the server the next day it won't reload at all.

**Comment by SRR8** [comment] 2021-12-13 15:25
I've fixed it. I removed it from the server, restarted the server without the mod, then restarted the server with the mod back on. No idea why this worked but it did.

**Comment by MrCrayfish** [comment] 2021-12-13 15:42
Let me know if it happens again. Did you restart the server between the off time when the mod was installed?

**Comment by Diamantino-Op** [comment] 2021-12-16 22:41
I'm having this problem too, i even tried recompiling mod from src too with no luck.

@MrCrayfish i may have found out after some debugging what is the problem

The code: if(ModSyncedDataKeys.RELOADING.getValue(player)) of class ReloadTracker can't get the value of the RELOADING Key

Edit:
found out more, this time is not in the Gun Mod but in the mod used to get and set the values of RELOADING (FrameWork), in the SyncedEntityData, in the methods get and set, the DataHolder holder = this.getDataHolder(entity); is always null.

**Comment by MrCrayfish** [comment] 2021-12-17 23:56
Can you tell me the steps to reproduce?

**Comment by Diamantino-Op** [comment] 2021-12-18 00:01
I just loaded up a test world and tried reloading

Btw, unloading works

For the denug, just put some System.out.println in the class

**Comment by MrCrayfish** [comment] 2021-12-18 00:03
You said `DataHolder holder = this.getDataHolder(entity);` is returning null but I don't get that result, even after reloading a world.

**Comment by Diamantino-Op** [comment] 2021-12-18 00:04
idk, i get null if i set a println in that

**Comment by MrCrayfish** [comment] 2021-12-18 00:05
Well not all entities have a data holder, only ones that have a Synced Key registered to them.

**Comment by Diamantino-Op** [comment] 2021-12-18 00:05
I modified like this:

public <E extends Entity, T> void set(E entity, SyncedDataKey<?, ?> key, T value)
    {
        if(!this.registeredDataKeys.contains(key))
        {
            throw new IllegalArgumentException(String.format("The synced data key %s for %s is not registered!", key.id(), key.classKey().id()));
        }
        DataHolder holder = this.getDataHolder(entity);
        System.out.println(CAPABILITY);
        if(holder != null && holder.set(entity, key, value))
        {
            if(!entity.level.isClientSide())
            {
                System.out.println("Set Data:" + key + " On: " + entity);
                this.dirty = true;
                this.dirtyEntities.add(entity);
            }
            else
                System.out.println("Entity is ClientSide");
        }
        else
            System.out.println("holder is null");
    }

**Comment by Diamantino-Op** [comment] 2021-12-18 00:05
and it only give result when i press R to reload

**Comment by MrCrayfish** [comment] 2021-12-18 00:07
Well `if(holder != null && holder.set(entity, key, value))` does not mean holder is null. It's possible for `set` to return false.

**Comment by Diamantino-Op** [comment] 2021-12-18 00:08
then, what is causing the not reload bug?

**Comment by MrCrayfish** [comment] 2021-12-18 00:09
Again, with no steps given to reproduce the issue, it's a lot harder to find the issue.

**Comment by Diamantino-Op** [comment] 2021-12-18 00:10
can you reload if you run from src?

**Comment by MrCrayfish** [comment] 2021-12-18 00:13
Yes, I developed the mod.

**Comment by Diamantino-Op** [comment] 2021-12-18 00:15
ok, i tried some more debug, and it arrives here:

@Override
    public void handle(MessageReload message, Supplier<NetworkEvent.Context> supplier)
    {
        supplier.get().enqueueWork(() ->
        {
            ServerPlayer player = supplier.get().getSender();
            if(player != null && !player.isSpectator())
            {
                ModSyncedDataKeys.RELOADING.setValue(player, message.reload); // This has to be set in order to verify the packet is sent if the event is cancelled

                System.out.println("Player Name: " + player + " Reload Bool: " + message.reload);

                if(!message.reload)
                    return;

                ItemStack gun = player.getMainHandItem();

                System.out.println("Gun: " + gun.getDisplayName());

                if(MinecraftForge.EVENT_BUS.post(new GunReloadEvent.Pre(player, gun))) <-------- HERE
                {
                    System.out.println("GunReload Pre");
                    ModSyncedDataKeys.RELOADING.setValue(player, false);
                    return;
                }
                MinecraftForge.EVENT_BUS.post(new GunReloadEvent.Post(player, gun));
            }
        });
        supplier.get().setPacketHandled(true);
    }

**Comment by Diamantino-Op** [comment] 2021-12-18 00:15
is it normal?

**Comment by MrCrayfish** [comment] 2021-12-18 00:17
Well if it's cancelled by the event, it's probably another mod cancelling the reloading.

**Comment by Diamantino-Op** [comment] 2021-12-18 00:17
what other mod?

**Comment by Diamantino-Op** [comment] 2021-12-18 00:17
i have only the three required

**Comment by Diamantino-Op** [comment] 2021-12-18 00:18
oh wait, maybe JEI?

**Comment by MrCrayfish** [comment] 2021-12-18 00:19
Okay, it's probably the event since it's only allowing the gun to reload if the event is cancelled.

**Comment by Diamantino-Op** [comment] 2021-12-18 00:19
ah

**Comment by MrCrayfish** [comment] 2021-12-18 00:21
Actually it's not the event. I didn't read the code completely.

**Comment by Diamantino-Op** [comment] 2021-12-18 00:21
then what is that?, bc it stops there the content of the if is never executed

**Comment by MrCrayfish** [comment] 2021-12-18 00:25
Read the code

**Comment by Diamantino-Op** [comment] 2021-12-18 00:27
ah yes, it stops reloading, my bad

**Comment by Diamantino-Op** [comment] 2021-12-18 00:40
Btw, now i can confirm that my holder is null when i try to reload

**Comment by Diamantino-Op** [comment] 2021-12-18 00:45
I added this code:

if (holder != null)
            System.out.println("Key: " + key + " Value: " + holder.set(entity, key, value) + " For: " + entity + " Value2: " + value);
        else
            System.out.println("Key: " + key + " Value: " + "Holder Null" + " For: " + entity + " Value2: " + value);

and it gave me "Holder Null" with the key cgm:reloading.

**Comment by MrCrayfish** [comment] 2021-12-18 00:57
Again Holder is not null for me.

**Comment by Diamantino-Op** [comment] 2021-12-18 00:58
idk then

**Comment by MrCrayfish** [comment] 2021-12-18 01:12
It's possible that I misconfigured the entity capability. Since you're able to replicate the issue.

In Framework, go to `SyncedEntityData` then `Provider` and replace `getCapability` with this below code.
```java
@Nonnull
@Override
public <T> LazyOptional<T> getCapability(@Nonnull Capability<T> cap, @Nullable Direction side)
{
    return cap == CAPABILITY ? this.optional.cast() : LazyOptional.empty();
}
```
then test it with the Gun Mod.

**Comment by Diamantino-Op** [comment] 2021-12-18 01:13
gimme a sec

**Comment by Diamantino-Op** [comment] 2021-12-18 01:16
nope

**Comment by Diamantino-Op** [comment] 2021-12-18 15:04
@MrCrayfish i fixed my issue, turns out that during debug i accidentally deleted @SubscribeEvent from the attachCapability function in the SyncedEntityData...

**Comment by Diamantino-Op** [comment] 2021-12-18 15:05
now it all works, and that fix should fix the previous bug

**Comment by Nightmarionne-1** [comment] 2022-01-12 16:27
idk what to do i have the same prob but i have no idea what to do ;w;

**Comment by MrCrayfish** [comment] 2022-07-13 14:09
Fixed in latest versions of 1.18.2 and above

**Closed as completed by MrCrayfish** 2022-07-13 14:09 UTC
