### ISSUE TITLE
Can't reload on 1.12.2

### ISSUE THREAD

**Issue by stayTranK2** [MrCrayfish/MrCrayfishGunMod#86] opened 2020-09-01 14:40 UTC
I can't reload, the keybinds are perfect, i have the ammo. What's happening?

**Comment by MrCrayfish** [comment] 2020-09-02 06:21
All I can think of is you're not using the correct ammo.

**Comment by Mateusz7073** [comment] 2020-11-26 13:46
I have same problem, Im playing on a mod pack and I was testing this mod on creative. I had every kind of ammo in inventory but reloading doesnt work for some reason, even with changed keybind, it must be conflicting with another mod

**Comment by jonnyGmod** [comment] 2021-01-11 00:18
I have different ammo in my inventory and it doesn't work what do i do to reload?

**Comment by MrCrayfish** [comment] 2021-02-03 12:17
Duplicate of https://github.com/MrCrayfish/MrCrayfishGunMod/issues/39

**Closed as completed by MrCrayfish** 2021-02-03 12:17 UTC
