### ISSUE TITLE
Invisible guns

### ISSUE THREAD

**Issue by FriendlyDispatch** [MrCrayfish/MrCrayfishGunMod#319] opened 2022-07-10 03:28 UTC
I can't see the guns

I have graphics below fabulous, and I can still see the minigun, bazooka, and grenade launcher

**Comment by MrCrayfish** [comment] 2022-07-13 14:45
Duplicate of https://github.com/MrCrayfish/MrCrayfishGunMod/issues/317

**Closed as completed by MrCrayfish** 2022-07-13 14:45 UTC
