### ISSUE TITLE
Game Crashes every now and then when joining a world.

### ISSUE THREAD

**Issue by IvorAmlug** [MrCrayfish/MrCrayfishGunMod#254] opened 2022-02-13 16:43 UTC
"The game crashed whilst ticking player
Error: java.lang.IllegalArgumentException: The synced data key cgm:aiming for minecraft:player is not registered!
Exit-Code: -1"
Full Crash Log here:
https://pastebin.com/HFM2f4yA

**Comment by CDAGaming** [comment] 2022-02-13 17:37
Have had this issue too, where it is unable to sync cgm:aiming for some reason.

**Comment by benpaq** [comment] 2022-02-14 23:03
same here, making a new world is often fine, but loading a saved world is where i crash.. but it worked on my server?

**Comment by MrCrayfish** [comment] 2022-02-15 00:47
Are you using the latest version of Framework?

**Comment by MrCrayfish** [comment] 2022-02-15 00:55
Duplicate of https://github.com/MrCrayfish/MrCrayfishGunMod/issues/241

**Closed as completed by MrCrayfish** 2022-02-15 00:55 UTC

**Comment by MrCrayfish** [comment] 2022-02-15 00:58
Just to summerize, this has been an issue for a while now. I've been struggling to create a fix since it's not as simple as it seems.
