### ISSUE TITLE
PIgman and Enderman

### ISSUE THREAD

**Issue by chaosnick44** [MrCrayfish/MrCrayfishGunMod#173] opened 2021-05-26 14:02 UTC
Hello! When i shoot near a pigman or enderman they get agressiv. (i dont shoot them) Pls fix it its annoying. Bye

**Comment by EnderiteFox** [comment] 2021-05-29 09:22
It is because they are panicking due to the noise, use a silencer to reduce the area where neutral mobs are panicking

**Comment by Ch1216** [comment] 2021-12-07 15:56
Does this still happen?, ive tested it and they dont seem to be agressive

**Comment by MrCrayfish** [comment] 2022-07-13 13:10
Duplicate of https://github.com/MrCrayfish/MrCrayfishGunMod/issues/163

**Closed as completed by MrCrayfish** 2022-07-13 13:10 UTC
