### ISSUE TITLE
Game keeps crashing with version 0.15.3-1.12.2

### ISSUE THREAD

**Issue by Alex22sv** [MrCrayfish/MrCrayfishGunMod#113] opened 2021-01-20 16:43 UTC
My friends and I have had issue with the mod and our games randomly crash while playing on the server, we have the same mods and version. Here is the minecraft log: https://mclo.gs/i2A90tz
![image](https://user-images.githubusercontent.com/70553543/105206671-3f9e3480-5b0c-11eb-8e59-ed7456c0ede9.png) I also include an image of the error I get when the game crashes.

**Comment by MrCrayfish** [comment] 2021-02-03 12:00
Duplicate of https://github.com/MrCrayfish/MrCrayfishGunMod/issues/30

**Closed as completed by MrCrayfish** 2021-02-03 12:00 UTC
